name: Tests

on:
  merge_group:
  pull_request:

jobs:
  test:
    name: Tests

    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for git-auto-commit-action.

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}  # Required in non-push events for git-auto-commit-action to work.

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml

      - name: Install dependencies
        run: uv sync --extra dev --frozen

      - name: Run pre-commit
        id: run-pre-commit
        continue-on-error: true
        uses: pre-commit/action@v3.0.1

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Apply pre-commit

      - name: Run tests
        run: uv run pytest tests/ --color=yes --cov=eva --cov-report=term-missing --durations=10

      - name: Fail if pre-commit failed
        if: steps.run-pre-commit.outcome == 'failure'
        run: exit 1
